[package]
name = "rustlang-bot"
version = "0.1.0"
authors = ["Rustlang-by community"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teloxide = "0.4"
log = "0.4.8"
pretty_env_logger = "0.4.0"
tokio = { version =  "1.3", features = ["rt-threaded", "macros"] }