[package]
name = "rustlang-bot"
version = "0.1.0"
authors = ["Rustlang-by community"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teloxide = { version = "0.4", features = ["auto-send"] }
log = "0.4.8"
pretty_env_logger = "0.4.0"
tokio = { version =  "1.4", features = ["rt-multi-thread", "macros"] }

regex = "1.4.5"
chrono = "0.4.19"

sqlx = { version = "0.5", features = [ "postgres", "runtime-tokio-native-tls", "chrono" ] }