[package]
name = "rust-bot"
version = "0.1.0"
authors = ["Rustlang-by community"]
edition = "2018"

[dependencies]
teloxide = { version = "0.5", features = ["auto-send", "macros"] }
log = "0.4.8"
pretty_env_logger = "0.4.0"
tokio = { version = "1.9", features = ["rt-multi-thread", "macros"] }

regex = "1.4.6"
chrono = "0.4.19"

sqlx = { version = "0.5", features = ["postgres", "runtime-tokio-native-tls", "chrono"] }